### Submit Mail (User only)
POST http://localhost:5001/api/mails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ5Mzg5MDEzLCJleHAiOjE3NDkzOTI2MTN9.z_-sM0Mp8c5MrUcv5gtwLGxOVNstYCmA1ESNJbyGnlg
Content-Type: application/json

{
  "url_file_surat": "https://example.com/surat123.pdf",
  "subject_surat": "Surat Tugas Penelitian"
}

### Get Template Surat Tugas
GET http://localhost:5001/api/mails/template
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ5MzY4NTA3LCJleHAiOjE3NDkzNzIxMDd9.G55O59f-CIjJsy29VNmYCHOl3zO741sdx8FkZoERiUw

### Get User's Mails
GET https://assigngo-mail-424905547173.us-central1.run.app/api/mails/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ5NTQyODgwLCJleHAiOjE3NDk1NDY0ODB9.b4ap7DRREzLHYvOhaqEvV4Nb_KhX7gpSp-Q8koM5FeE

### Get Mail Details
GET http://localhost:5001/api/mails/details/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ5Mzg4Njg5LCJleHAiOjE3NDkzOTIyODl9.N0iIX91a4AtktJONdE9dW-0rDYRUETDQhxC16eo5Dos

### Get Mail History
GET https://assigngo-mail-424905547173.us-central1.run.app/api/history/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ5NTQyODgwLCJleHAiOjE3NDk1NDY0ODB9.b4ap7DRREzLHYvOhaqEvV4Nb_KhX7gpSp-Q8koM5FeE

### Get All Mails (Admin only)
GET http://localhost:5001/api/mails
Authorization: Bearer admin-token-here

### Get Mail Stats (Admin only)
GET http://localhost:5001/api/mails/stats
Authorization: Bearer admin-token-here

### Update Mail Status to Disetujui (Admin only)
POST http://localhost:5001/api/history/1
Authorization: Bearer admin-token-here
Content-Type: application/json

{
  "status": "disetujui"
}

### Update Mail Status to Ditolak (Admin only)
POST http://localhost:5001/api/history/2
Authorization: Bearer admin-token-here
Content-Type: application/json

{
  "status": "ditolak",
  "alasan": "Format surat tidak sesuai dengan ketentuan"
}
###
POST https://assigngo-mail-424905547173.us-central1.run.app/api/mails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ5NTQyODgwLCJleHAiOjE3NDk1NDY0ODB9.b4ap7DRREzLHYvOhaqEvV4Nb_KhX7gpSp-Q8koM5FeE
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="subject_surat"

Surat Tugas Penelitian
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file_surat"; filename="testlagigass.pdf"
Content-Type: application/pdf

< ./Secret/test.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--