### Submit Mail (User only)
POST http://localhost:5001/api/mails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ5Mzg4NzQzLCJleHAiOjE3NDkzOTIzNDN9.bNs90u2qks6AvYPjrHuc491LQgpvMTweUrpw0ilxBso
Content-Type: application/json

{
  "url_file_surat": "https://example.com/testke2kata-rafly-gabisapdf",
  "subject_surat": "Surat Tugas Penelitian"
}

### Get Template Surat Tugas
GET http://localhost:5001/api/mails/template
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ5MzY4NTA3LCJleHAiOjE3NDkzNzIxMDd9.G55O59f-CIjJsy29VNmYCHOl3zO741sdx8FkZoERiUw

### Get User's Mails
GET http://localhost:5001/api/mails/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ5Mzc1Mzk4LCJleHAiOjE3NDkzNzg5OTh9.qpowsfCfXCIT3Iiq5gNts-LuCGPkjSiMPwzKLPv2k00

### Get Mail Details
GET http://localhost:5001/api/mails/details/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ5Mzg4Njg5LCJleHAiOjE3NDkzOTIyODl9.N0iIX91a4AtktJONdE9dW-0rDYRUETDQhxC16eo5Dos

### Get Mail History
GET http://localhost:5001/api/history/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ5Mzc1NTAzLCJleHAiOjE3NDkzNzkxMDN9.a_SSGM66TjZIBwZXDhHf5CskQl4SHfWqQ_vSSIOwCWs

### Get All Mails (Admin only)
GET http://localhost:5001/api/mails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0OTM3NTI5MiwiZXhwIjoxNzQ5Mzc4ODkyfQ.GgoEetXqJEBT2YRoSUHtb-29GhinCQi-9STc3bKc1dw

### Get Mail Stats (Admin only)
GET http://localhost:5001/api/mails/stats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0OTM3NTI5MiwiZXhwIjoxNzQ5Mzc4ODkyfQ.GgoEetXqJEBT2YRoSUHtb-29GhinCQi-9STc3bKc1dw

### Update Mail Status to Disetujui (Admin only)
POST http://localhost:5001/api/history/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0OTM3NTI5MiwiZXhwIjoxNzQ5Mzc4ODkyfQ.GgoEetXqJEBT2YRoSUHtb-29GhinCQi-9STc3bKc1dw
Content-Type: application/json

{
  "status": "disetujui"
}

### Update Mail Status to Ditolak (Admin only)
POST http://localhost:5001/api/history/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0OTM3NTE5OSwiZXhwIjoxNzQ5Mzc4Nzk5fQ.DWgdmbtj2clhoVqnTDLZDRY3vK_pG9YnrH_NujHIyL4
Content-Type: application/json

{
  "status": "ditolak",
  "alasan": "Format surat tidak sesuai dengan ketentuan"
}
###
POST http://localhost:5004/api/mails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ5MzkxMDk4LCJleHAiOjE3NDkzOTQ2OTh9.WzfJcMTQ58T3rlrianldTupOA-Eh_xEgGcvE-tlb_sw
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="subject_surat"

Surat Tugas Penelitian
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file_surat"; filename="test.pdf"
Content-Type: application/pdf

< ./Secret/test.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--